---
- name: Install mongodb package
  apt:
    pkg:
    - mongodb
    - net-tools
    state: present
    update_cache: yes
  notify:
    - restart mongodb

- name: Change magodb config file
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    mode: 0644
  notify:
    - restart mongodb

