driver:
  name: vagrant
provider:
  name: virtualbox
  #lint:
  # name: yamlint
platforms:
  - name: instance
    box: ubuntu/focal64
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
lint: |
  name: ansible-lint
verifier:
  name: testinfra
